### PR TITLE
Apple ProRes support

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Review by JonnyBurger — APPROVED** [review]
Thanks a lot! Awesome idea 💙  🙌

**Comment by wcandillon** [comment]
Amazing, it looks like the pixel format needs to be yuva444p10le, I'm getting: `Incompatible pixel format 'yuva420p' for codec 'prores_ks', auto-selecting format 'yuva444p10le'`

**Comment by JonnyBurger** [comment]
@wcandillon We don't set `yuva420p` automatically, did you by any chance set it in your config file explicitly? If so, removing it may fix it.

**Comment by wcandillon** [comment]
indeed, I just thought maybe that yuva444p10le should be an allowed value maybe? 🤷‍♂️

**Comment by JonnyBurger** [comment]
@wcandillon Good point, made another issue about it!

**Pull request merged**
