### PR TITLE
Add `yarn create video` on homepage

### PR DESCRIPTION
**Pull request by Tobijudah**
67 - localhost_3000_(Laptop with MDPI screen)

#266

### CODE REVIEW

**Comment by Tobijudah** [comment]
@JonnyBurger what do you think?

Also, when I followed the instructions on *CONTRIBUTING.md* several package-lock.json files were updated, should I push those changes as well?

**Comment by Iamshankhadeep** [comment]
Lgtm. Let @JonnyBurger review it.

**Review by Iamshankhadeep — APPROVED** [review]
Lgtm. Let's wait for @JonnyBurger review.

**Comment by abhijit-hota** [comment]
I think we should use the `npx create-video` as the primary snippet and `yarn create video` as a secondary one.

**Comment by JonnyBurger** [comment]
Thank you @Tobijudah! Looking good, and is also pretty much what I had in mind!
Thanks a lot for sending this contribution! 💙 

@abhijit-hota I think it's pretty equivalent, do you see any benefit? So far we've gone for `yarn create video` in all our resources, so for consistency I would prefer it. There is also `npm init video` which IMO reads cooler.

**Comment by abhijit-hota** [comment]
>  do you see any benefit? 

Nothing as such. I personally prefer Yarn but most of the examples you provided in #266 show the `npm` script. If we're using yarn everywhere, then there's no added benefit.

>  There is also npm init video which IMO reads cooler.

Oh! Didn't know that.

**Comment by JonnyBurger** [comment]
@abhijit-hota Got it! Makes sense.

A further iteration would be to have something like React Navigation where you can select your package manager: 

image

It may also default to NPM.

**Comment by abhijit-hota** [comment]
Ah ,yes. Cool!

**Pull request merged**
