### PR TITLE
Persist preview size option

### PR DESCRIPTION
**Pull request by Tobijudah**
#239 

@JonnyBurger is there a way I can run a local version of the Editor to test my changes?

### CODE REVIEW

**Comment by JonnyBurger** [comment]
@Tobijudah  Yes, go to `packages/example` and run `npm start`!

**Comment by JonnyBurger** [comment]
I tested it out and it works well for me! Happy to merge as it is.
I am waiting until you mark the PR as ready for review.

**Comment by JonnyBurger** [comment]
By the way, I broke the preview in a previous commit, sorry about that, pull and it should be fixed!

**Comment by Tobijudah** [comment]
Alright then, haven't gotten my changes to reflect locally here yet even as I ran npm test in the example folder. Perhaps I'm missing something. Since it's all well on your end then you can merge!
Thanks

**Review by JonnyBurger — APPROVED** [review]

**Comment by JonnyBurger** [comment]
Thanks a lot for the PR! 💙 🙌  Very helpful and you nailed it the first time 😊

**Pull request merged**
