### PR TITLE
gifs 🚀

### PR DESCRIPTION
**Pull request by jeetiss**
### gif component for remotion

it uses my library for gifs [jeetiss/react-gifs](https://github.com/jeetiss/react-gifs), is it okey ?)

component in review mode
- parses gifs in web worker and shows frame by frame
- uses lru cache for fast mounting or rerendering

in render mode
- parses gifs in main thread because remotion already has concurrency 
- no lru cache

TODOs:
- [x] fix transparency https://github.com/jeetiss/react-gifs/issues/1
- [x] error handling (??)
- [x] forward ref to canvas (??)
- [x] tests
- [ ] something else

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Pure awesomeness!!
We can ship this in this repo, but I want to extract it to a new package, like `@remotion/gif`. Because not everybody needs it and soon you can import `remotion` package on your website when you want to embed a video on your website.

I can do this refactor and add documentation for it if you like or you can also give it a try! I'll post here if I start doing some refactors.

**Comment by jeetiss** [comment]
>  I want to extract it to a new package, like `@remotion/gif`.

I like this way to 👍🏻

> I can do this refactor and add documentation for it if you like or you can also give it a try

I will try, but I need help with documentation 🙈

**Comment by JonnyBurger** [comment]
OK I can take care of writing the docs!

Will first take care of shipping Remotion 2.0 with Audio though, but I will not forget this awesome PR 😊 

PS: If you want to get paid for your work on Remotion, reply to my Twitter DM

**Comment by JonnyBurger** [comment]
I just tested this, this is awesome!!
From what I understand, this is WIP on your side, but whenever you are happy, I will merge it.

**Comment by jeetiss** [comment]
@JonnyBurger PR is ready 🙌🏻
finally I finish this

**Comment by JonnyBurger** [comment]
@jeetiss Niice! I did revert the changes to `core` package, should not be necessary anymore.

Will soon check out and review again, hopefully can merge it soon 🙌

**Review by JonnyBurger — APPROVED** [review]

**Comment by JonnyBurger** [comment]
Thanks a lot 💙 !
Awesome work. I added some documentation and another test as well, and I will feature it in the Remotion 2.0 announcement video 🙌

**Pull request merged**
