### PR TITLE
Add Performance Tips to docs

### PR DESCRIPTION
**Pull request by Tobijudah**
image

### CODE REVIEW

**Comment by Tobijudah** [comment]
Closes #301

**Comment by Tobijudah** [comment]
@JonnyBurger

**Comment by JonnyBurger** [comment]
@Tobijudah sorry for the delay in processing this PR!
I'll get to it on Thursday for sure!

**Comment by Tobijudah** [comment]
Sure man, just wanted to be sure it's not been forgotten 😅

**Comment by JonnyBurger** [comment]
Surely not 🙂
I wanted to add some tips and write them out before putting it up. I turned this into the first article in the troubleshooting section! More of those are coming. Thanks a lot for initiating the PR 😊

**Review by JonnyBurger — APPROVED** [review]

**Pull request merged**
